// 29 gyógytorna gyakorlat a gyógytorna_gyakorlatok.txt alapján
// eszkoz: enyhe definíció — törölköző/párna/matrac/jógatégla-fejalátét NEM számít eszköznek.
// Eszköznek számít: kislabda (overball), jógatégla (emelvényként), fitball, miniband/gumiszalag, bordásfal, csúszka.
window.EXERCISES = [
{id:1,blokk:"Idegmobilizáció, mellkasnyitás",nev:"Ülőideg mobilizáció (sciatic glide)",kiindulo:"Hanyattfekvés. Egyik láb nyújtva pihen, másik térd két kézzel felhúzva a váll felé.",lepesek:["Felhúzott helyzetben a lábfej pipál, visszafeszíted.","Combot tartva a lábszárat kinyújtod felfelé, közben spiccelsz.","Visszahajlítod a térdet a vállhoz, újra pipálsz.","Folyamatos ritmikus mozgással ismétled."],ismetles:"3×10 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:180,tts:"Ülőideg mobilizáció. Feküdj hanyatt. Húzd fel egyik térded a válladhoz. Pipál, nyújt, spiccel. Ritmikusan ismételd."},
{id:2,blokk:"Idegmobilizáció, mellkasnyitás",nev:"Mellkasnyitás kislabdán",kiindulo:"Hanyattfekvés, kislabda a lapockák alatt, fej alatt párna. Karok a test mellett.",lepesek:["Engedd rá a testsúlyod a labdára.","Mindkét nyújtott karral nyújtózz hátra a fül mellé.","Tartsd meg röviden a nyújtást.","Lassan engedd vissza a karokat."],ismetles:"5–10 db",eszkoz:["kislabda"],oldal:"kozepes",tartasMp:3,becsultMp:120,tts:"Mellkasnyitás kislabdán. Feküdj a labdára. Karokkal nyújtózz hosszan hátra a fül mellé, majd engedd vissza."},
{id:3,blokk:"Idegmobilizáció, mellkasnyitás",nev:"Karemelés plafon felé oldalfekvésben",kiindulo:"Oldalfekvés egyenesen, labda a bokák közt. Alsó kar a fej alatt, medence stabil.",lepesek:["Nagy belégzés, ellazulás.","Kilégzésre köldök behúz, farizom feszít.","Felülső nyújtott kart emeld függőlegesig.","Lassan engedd vissza, medence mozdulatlan."],ismetles:"5–5 oldalanként",eszkoz:["kislabda"],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Oldalfekvésben karemelés. Stabil medencével emeld a felülső kart a plafon felé, majd engedd vissza."},
{id:4,blokk:"Idegmobilizáció, mellkasnyitás",nev:"Karkörzés plafon felé nyújtott karral",kiindulo:"Stabil oldalfekvés, labda a bokák közt. Felülső kar függőlegesen a plafon felé.",lepesek:["Kilégzésre nagy kört rajzolsz a nyújtott karral.","Félúton megállsz, belégzel.","Ellenkező irányba újabb kör.","Törzs nem forog, nem billeg."],ismetles:"6 kilégzés (3 előre, 3 hátra)",eszkoz:["kislabda"],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Karkörzés oldalfekvésben. Rajzolj nagy köröket a nyújtott karral, törzsed mozdulatlan marad."},
{id:5,blokk:"Négykézláb, térdelőtámasz",nev:"Ellentétes kar- és lábemelés (Bird-Dog)",kiindulo:"Négykézláb: vállszéles tenyér, csípőszéles térd. Nyak egyenes, derék természetes.",lepesek:["Egyik láb hátracsúsztat lábujjhegyre, csípő párhuzamos.","Kilégzésre emeld a nyújtott lábat törzsvonalig, sarokkal hátra.","Ellentétes kart emeld előre a fül mellé.","Tartsd 5 másodpercig, majd csere."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:5,becsultMp:180,tts:"Bird dog. Négykézláb. Emeld ellentétes kart és lábat vízszintesig. Tartsd öt másodpercig."},
{id:6,blokk:"Négykézláb, térdelőtámasz",nev:"Bird-Dog kislabdás instabilitással",kiindulo:"Négykézláb, támaszkodó lábszár alatt puha kislabda.",lepesek:["Szabad láb hátra a talajra.","Kilégzésre emeld törzsvonalba, sarokkal hátra.","Ellentétes kart előre a fül mellé.","Tartsd 5–10 mp-ig egyensúlyozva, majd csere."],ismetles:"5–5 oldalanként",eszkoz:["kislabda"],oldal:"oldalankent",tartasMp:7,becsultMp:200,tts:"Bird dog labdán. A támasz lábad alatt kislabda van. Emeld ellentétes kart és lábat, egyensúlyozz."},
{id:7,blokk:"Négykézláb, térdelőtámasz",nev:"Medenceszintezés térdelőtámaszban",kiindulo:"Négykézláb, egyik térd jógatéglán, másik a levegőben lóg mellette.",lepesek:["Belégzés kiinduló helyzetben.","Kilégzésre has feszít, lebillent csípőfelet vízszintbe emeled.","Törzs nem dől oldalra.","Lassan vissza lebillenni."],ismetles:"5–5 oldalanként",eszkoz:["jogategla"],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Medenceszintezés. Egyik térded téglán. Kilégzésre emeld a lógó csípőfelet vízszintesbe."},
{id:8,blokk:"Hasonfekvő lapocka (I, W, Y)",nev:"„I” betű karkiemelés hasonfekvésben",kiindulo:"Hasonfekvés, homlok alatt kis párna. Karok hátra nyújtva test mellett.",lepesek:["Vállakat húzd hátra-felfelé, lapockák zárnak.","Emeld fel a nyújtott karokat, nyújtózz a bokák felé.","Tartsd 3–5 másodpercig.","Lassan engedd vissza."],ismetles:"10 db",eszkoz:[],oldal:"kozepes",tartasMp:4,becsultMp:120,tts:"I betű hason. Karok test mellett hátra. Emeld fel a karokat, lapockákat zárd. Tartsd ki."},
{id:9,blokk:"Hasonfekvő lapocka (I, W, Y)",nev:"„W” betű karhúzás hasonfekvésben",kiindulo:"Hasonfekvés, kezek tarkón, könyökök a talajon.",lepesek:["Könyököket emeld fel a plafon felé.","Húzd hátra W formába, lapockák zárnak.","Érintsd vissza a kezed a tarkódhoz.","Engedd le a talajra."],ismetles:"10 db",eszkoz:[],oldal:"kozepes",tartasMp:0,becsultMp:120,tts:"W betű hason. Kezek tarkón. Emeld a könyököt, húzd W-be, majd vissza a tarkóhoz."},
{id:10,blokk:"Hasonfekvő lapocka (I, W, Y)",nev:"Összetett I – W – Y – W – I",kiindulo:"Hasonfekvés, homlok alátámasztva.",lepesek:["Karok hátra I betűbe.","Felhúzás W betűbe a levegőben.","Kinyújtás rézsút előre Y betűbe.","Vissza W-be, majd I-be, letesz."],ismetles:"5 ciklus",eszkoz:[],oldal:"kozepes",tartasMp:0,becsultMp:150,tts:"Összetett gyakorlat. I, W, Y, W, I. Lassan, lapockákat végig zárva."},
{id:11,blokk:"Hasizom, törzs",nev:"Hasprés térdnyújtással",kiindulo:"Hanyattfekvés, lábak talpon, kezek tarkón, könyök nyitva.",lepesek:["Apró hasprés: felsőtest plafon felé.","Ezzel egyik térd kinyújt ferdén felfelé.","Tartsd 10 másodpercig.","Lecsere, másik lábbal."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:10,becsultMp:220,tts:"Hasprés térdnyújtással. Apró hasprés, egyik láb ferdén kinyújt. Tartsd tíz másodpercig."},
{id:12,blokk:"Hasizom, törzs",nev:"Oldalsó félplank medenceemeléssel",kiindulo:"Oldalfekvés, alkar jógatéglán, könyök váll alatt. Térdek hajlítva.",lepesek:["Mély belégzés.","Kilégzésre köldök behúz, medence fel.","Tartsd ki amíg fújod a levegőt.","Lassan engedd le."],ismetles:"5–5 oldalanként",eszkoz:["jogategla"],oldal:"oldalankent",tartasMp:5,becsultMp:200,tts:"Oldalsó félplank. Tolod ki a mellkast. Kilégzésre emeld a medencét magasra."},
{id:13,blokk:"Hasizom, törzs",nev:"Döglött bogár 1 – talpérintés",kiindulo:"Hanyattfekvés. Karok plafon felé, csípő-térd 90 fok. Derék lesimítva.",lepesek:["Kilégzésre has aktív.","Térdszöget tartva egyik sarok érinti a talajt.","Derék nem emelkedik fel.","Vissza, majd csere."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Döglött bogár egy. Karok fent, lábak kilencven fokban. Egyik sarok leérint, derék lent marad."},
{id:14,blokk:"Hasizom, törzs",nev:"Döglött bogár 2 – lábnyújtás előre",kiindulo:"Ugyanaz a döglött bogár helyzet.",lepesek:["Kilégzésre has feszít.","Egyik láb kinyújt előre, sarok 10 cm-re megáll.","Visszahúz 90 fokba.","Másik lábbal ismét."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Döglött bogár kettő. Egyik láb kinyújt előre alacsonyan, majd vissza."},
{id:15,blokk:"Hasizom, törzs",nev:"Döglött bogár 3 – ellentétes kar-láb",kiindulo:"Döglött bogár kiinduló helyzet.",lepesek:["Kilégzésre köldök behúz.","Egyik láb előre, ellentétes kar hátra nyújt.","Derék lesimítva marad.","Vissza, majd csere."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:170,tts:"Döglött bogár három. Ellentétes kar és láb nyújt egyszerre. Derék mozdulatlan."},
{id:16,blokk:"Hasizom, törzs",nev:"Szfinx póz (lazítás)",kiindulo:"Hasonfekvés, alkarokon támaszkodva.",lepesek:["Medence és has belesüpped a matracba.","Derék ellazul.","Mély kilégzéssel köldök süllyed.","Néhány mély lélegzet."],ismetles:"pár lélegzet",eszkoz:[],oldal:"kozepes",tartasMp:0,becsultMp:60,tts:"Szfinx póz, lazítás. Engedd bele a hasad a matracba. Mélyeket lélegezz."},
{id:17,blokk:"Hasizom, törzs",nev:"Döglött bogár 4 – lábnyitás oldalra",kiindulo:"Döglött bogár kiinduló helyzet.",lepesek:["Kilégzésre egyik térd kinyílik oldalra.","Csak addig, míg a medence nem billen.","Vissza középre.","Másik oldal."],ismetles:"5–5 oldalanként",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Döglött bogár négy. Térd kinyílik oldalra, medence a talajon marad."},
{id:18,blokk:"Híd, medenceemelés",nev:"Alap medenceemelés (híd)",kiindulo:"Hanyattfekvés, talpak csípőszélességben. Karok test mellett.",lepesek:["Farizom erősen szorít.","Medence kiemel comb-törzs egy vonalig.","Tartsd 5 másodpercig szorítva.","Lassan le, lent lazít."],ismetles:"5 db",eszkoz:[],oldal:"kozepes",tartasMp:5,becsultMp:120,tts:"Alap híd. Szorítsd a farizmot. Emeld a medencét egy vonalba. Tartsd öt másodpercig."},
{id:19,blokk:"Híd, medenceemelés",nev:"Medenceemelés emelt karokkal",kiindulo:"Hanyattfekvés talptámasszal, karok plafon felé nyújtva.",lepesek:["Farizom szorítás, medence kiemel.","Térdek nem nyílnak szét.","Tartsd 5 másodpercig.","Lassan vissza."],ismetles:"kb. 10 db",eszkoz:[],oldal:"kozepes",tartasMp:5,becsultMp:150,tts:"Híd emelt karokkal. Karok a plafon felé. Emeld a csípőt, térdek párhuzamosak."},
{id:20,blokk:"Híd, medenceemelés",nev:"Híd váltott térdhúzással",kiindulo:"Híd tartás, karok plafon felé, csípő egy magasságban.",lepesek:["Fent tartott medencével egyik térd hashoz húz.","Talp vissza.","Másik térd felhúz.","Csípő végig fent marad."],ismetles:"3 kör (2-2 lépés)",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Híd térdhúzással. Csípő fent marad. Váltva húzd a térdeket a hashoz."},
{id:21,blokk:"Híd, medenceemelés",nev:"Híd váltott lábnyújtással",kiindulo:"Híd tartás, karok plafon felé.",lepesek:["Fent tartott csípővel egyik térd kinyújt előre.","Combok párhuzamosak maradnak.","Talp vissza, másik láb.","Csípő nem süllyed."],ismetles:"3 kör (2-2 nyújtás)",eszkoz:[],oldal:"oldalankent",tartasMp:0,becsultMp:150,tts:"Híd lábnyújtással. Csípő fent. Váltva nyújtsd ki a lábakat előre."},
{id:22,blokk:"Híd, medenceemelés",nev:"Medenceemelés fitballon",kiindulo:"Hanyattfekvés, sarkak a fitball tetején. Karok test mellett.",lepesek:["Farizommal medence kiemel egyenes vonalig.","Egyensúlyozz a labdán.","Tartsd 5 másodpercig.","Lassan le."],ismetles:"5–10 db",eszkoz:["fitball"],oldal:"kozepes",tartasMp:5,becsultMp:150,tts:"Híd fitballon. Sarkak a labdán. Emeld a medencét, egyensúlyozz."},
{id:23,blokk:"Híd, medenceemelés",nev:"Medenceemelés fitballon emelt karokkal",kiindulo:"Sarkak fitballon, karok plafon felé nyújtva.",lepesek:["Farizom maximális szorítás, medence fel.","Egyensúlyozz, tartsd 5 mp-ig.","Lassan engedd vissza."],ismetles:"5–10 db",eszkoz:["fitball"],oldal:"kozepes",tartasMp:5,becsultMp:160,tts:"Híd fitballon emelt karral. Nehezített egyensúly. Tartsd öt másodpercig."},
{id:24,blokk:"Híd, medenceemelés",nev:"Medenceemelés gumiszalaggal",kiindulo:"Hanyattfekvés talptámasszal, miniband a térdek körül. Karok fent.",lepesek:["Hídba emel farizommal.","Fent tartva térdek szétnyit 3-szor a szalag ellen.","Zár vissza párhuzamosig.","Harmadik után medence le."],ismetles:"3 kör (3 nyitással)",eszkoz:["miniband"],oldal:"kozepes",tartasMp:0,becsultMp:150,tts:"Híd gumiszalaggal. Fent tartott csípővel háromszor nyisd a térdeket."},
{id:25,blokk:"Híd, medenceemelés",nev:"Híd gumikötél-lehúzással",kiindulo:"Hanyattfekvés a bordásfal előtt, gumiszalag végei kézben.",lepesek:["Medence kiemel hídba.","Fent tartva szalag lehúz combok mellé.","Visszaenged fej fölé, 3-szor.","Medence le."],ismetles:"3 kör (3 lehúzással)",eszkoz:["gumiszalag","bordasfal"],oldal:"kozepes",tartasMp:0,becsultMp:170,tts:"Híd gumilehúzással. Csípő fent. Húzd le a szalagot a combok mellé háromszor."},
{id:26,blokk:"Tigris, csúszkás",nev:"Statikus Tigris póz",kiindulo:"Négykézláb, lábujjak visszafeszítve.",lepesek:["Nagy belégzés.","Kilégzésre köldök behúz.","Mindkét térd 1 cm-re elemel.","Tartsd amíg fújod, majd letesz."],ismetles:"3–5 db",eszkoz:[],oldal:"kozepes",tartasMp:0,becsultMp:120,tts:"Tigris póz. Négykézláb. Térdeket egy ujjnyira emeld fel. Tartsd ki."},
{id:27,blokk:"Tigris, csúszkás",nev:"Tigris lábcsúsztatással hátra",kiindulo:"Lebegő tigris, egyik lábfej alatt csúszka.",lepesek:["Törzs stabil, csúsztasd hátra egyenesre.","Kilégzéssel húzd vissza.","Térd végig 1 cm-en lebeg.","Támasz térd nem emelkedik."],ismetles:"5–5 oldalanként",eszkoz:["csuszka"],oldal:"oldalankent",tartasMp:0,becsultMp:170,tts:"Tigris csúsztatással hátra. Egyik láb csúszkán hátra, majd vissza. Törzs stabil."},
{id:28,blokk:"Tigris, csúszkás",nev:"Tigris lábcsúsztatással oldalra",kiindulo:"Lebegő tigris, egyik láb alatt csúszka.",lepesek:["Kilégzésre láb kicsúsztat oldalra.","Medence nem fordul el.","Lassan vissza."],ismetles:"5–5 oldalanként",eszkoz:["csuszka"],oldal:"oldalankent",tartasMp:0,becsultMp:170,tts:"Tigris oldalra csúsztatással. Láb oldalra ki, medence nem fordul."},
{id:29,blokk:"Tigris, csúszkás",nev:"Tigris lábkörzéssel csúszkán",kiindulo:"Lebegő tigris, egyik láb alatt csúszka.",lepesek:["Hátra csúsztat, ívben oldalra, vissza.","Majd oldalra ki, ívben hátra, vissza.","Másik térd stabilan lebeg 1 cm-en."],ismetles:"5–5 kör irányonként",eszkoz:["csuszka"],oldal:"oldalankent",tartasMp:0,becsultMp:220,tts:"Tigris körzéssel. Nagy köröket rajzolsz a csúszkás lábbal, mindkét irányba."}
];
window.ESZKOZ_LABEL = {kislabda:"kislabda",jogategla:"jógatégla",fitball:"fitball",miniband:"miniband",gumiszalag:"gumiszalag",bordasfal:"bordásfal",csuszka:"csúszka"};
